sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t joshigaurav/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true joshigaurav/react-test npm test

after_success:
  - docker build -t joshigaurav/multi-client ./client
  - docker build -t joshigaurav/multi-nginx ./nginx
  - docker build -t joshigaurav/multi-server ./server
  - docker build -t joshigaurav/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password -stdin

  # Push these images to docker hub
  - docker push joshigaurav/multi-client
  - docker push joshigaurav/multi-nginx
  - docker push joshigaurav/multi-server
  - docker push joshigaurav/multi-worker

